# Generated by Django 3.2.3 on 2022-05-19 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='University',
        ),
    ]
