# Generated by Django 3.2.3 on 2022-05-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaceStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_year', models.CharField(max_length=20)),
                ('race_round', models.CharField(max_length=10)),
                ('race_standing', models.CharField(max_length=10000)),
            ],
        ),
    ]
