# Generated by Django 3.2.16 on 2022-11-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20221121_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='artitem',
            name='img_url',
            field=models.URLField(default='https://www.linkpicture.com/q/LPic6370e982af0ad569150138.png'),
        ),
        migrations.AlterField(
            model_name='artitem',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
