# Generated by Django 3.2.16 on 2022-11-30 18:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20221128_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artitem',
            name='comments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='artitem',
            name='date',
            field=models.DateField(default='2022-01-01'),
        ),
        migrations.AlterField(
            model_name='artitem',
            name='description',
            field=models.CharField(default='description', max_length=512),
        ),
        migrations.AlterField(
            model_name='artitem',
            name='favourites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='artitem',
            name='image',
            field=models.TextField(default='base64-encoded'),
        ),
        migrations.AlterField(
            model_name='artitem',
            name='owner_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='artitem',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default='2022-01-01'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='owner_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(default='comment', max_length=1024),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='art_items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='date',
            field=models.DateField(default='2022-01-01'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='location',
            field=models.CharField(default='Istanbul', max_length=100),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='owner_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='type',
            field=models.CharField(default='physical', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateField(default='2022-01-01'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='receiver_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.CharField(default='notification', max_length=1024),
        ),
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(default='tag', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='art_items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='user',
            name='comments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='exhibitions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='favourites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='followings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(default='Istanbul', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='notifications',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='Password123!', max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='token', max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='username', max_length=100),
        ),
    ]
