# Generated by Django 3.2.16 on 2022-12-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20221130_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='description',
            field=models.CharField(default='exhibition description', max_length=500),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='end_time',
            field=models.TimeField(default='13:00'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='name',
            field=models.CharField(default='exhibition name', max_length=100),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='open_address',
            field=models.CharField(default='Picasso Caddesi No:26/7 Beylikduzu/Istanbul', max_length=500),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='start_time',
            field=models.TimeField(default='10:30'),
        ),
    ]
