# Generated by Django 3.2.3 on 2022-05-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.CharField(max_length=256)),
                ('country_name', models.CharField(max_length=256)),
                ('country_id', models.CharField(max_length=40)),
                ('updated_on', models.DateTimeField()),
            ],
        ),
    ]
