# Generated by Django 3.2.3 on 2022-05-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('institute_name', models.CharField(max_length=40)),
                ('degree', models.CharField(max_length=80)),
                ('end_year', models.IntegerField()),
            ],
        ),
    ]
