# Generated by Django 3.2.3 on 2022-05-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.CharField(max_length=5),
        ),
    ]
